name: flutter_sms_listener
description: Flutter plugin to listen for incoming SMS on Android.
version: 1.0.0
homepage: https://github.com/popgas-admin/flutter_sms_listener

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: br.com.popgas.flutter_sms_listener
        pluginClass: FlutterSmsListenerPlugin
